const fs = require('fs');
let c = fs.readFileSync('index.html', 'utf8');
c = c.replace('class="summary-loop-num">\u7b2c', 'class="summary-loop-num" data-i18n="loop.loopComplete">\u7b2c');
c = c.replace('class="summary-outro">\u606d\u559c', 'class="summary-outro" data-i18n="loop.congratsClear">\u606d\u559c');
c = c.replace('class="summary-tokens">', 'class="summary-tokens" data-i18n="loop.tokensEarned">');
c = c.replace('class="summary-token-detail">(', 'class="summary-token-detail" data-i18n="loop.tokenDetail">(');
c = c.replace('class="summary-token-balance">\u5b66\u56ed', 'class="summary-token-balance" data-i18n="loop.tokenBalance">\u5b66\u56ed');
c = c.replace('class="summary-shop-title">', 'class="summary-shop-title" data-i18n="loop.shopTitle">');
c = c.replace('class="summary-next">\u4e0b\u4e00\u8f6e', 'class="summary-next" data-i18n="loop.nextLoop">\u4e0b\u4e00\u8f6e');
c = c.replace('class="summary-next-btn">\u8fdb\u5165', 'class="summary-next-btn" data-i18n="loop.nextBtn">\u8fdb\u5165');
c = c.replace('style="display: none">\u5956\u52b1', 'style="display: none" data-i18n="loop.rewardBadge">\u5956\u52b1');
c = c.replace('class="collection-tab active" data-tab="items"', 'class="collection-tab active" data-tab="items" data-i18n="collection.tabItems"');
c = c.replace('class="collection-tab" data-tab="gacha">', 'class="collection-tab" data-tab="gacha" data-i18n="collection.tabGacha">');
c = c.replace('class="collection-tab" data-tab="fragments">', 'class="collection-tab" data-tab="fragments" data-i18n="collection.tabFragments">');
c = c.replace(/<div class="rotate-text">\s*&#x8BF7;&#x65CB;&#x8F6C;&#x56DE;&#x7AD6;&#x5C4F;&#x6A21;&#x5F0F;<br\s*\/>&#x4EE5;&#x83B7;&#x5F97;&#x6700;&#x4F73;&#x4F53;&#x9A8C;\s*<\/div>/, '<div class="rotate-text" data-i18n="landscape.warning">\u8bf7\u65cb\u8f6c\u56de\u7ad6\u5c4f\u6a21\u5f0f\u4ee5\u83b7\u5f97\u6700\u4f73\u4f53\u9a8c</div>');
fs.writeFileSync('index.html', c, 'utf8');
console.log('Done');